apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "friends-service-backend.fullname" . }}
  labels:
    {{- include "friends-service-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "friends-service-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "friends-service-backend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "friends-service-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "friends-service-backend.fullname" . }}-config
            - secretRef:
                name: {{ include "friends-service-backend.fullname" . }}-secret
          volumeMounts:
            - name: static
              mountPath: /app/staticfiles
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: {{ include "friends-service-backend.fullname" . }}-static
        - name: tmp
          emptyDir: {}