apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "auth-service-backend.fullname" . }}-static
  labels:
    {{- include "auth-service-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
