apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service-backend.fullname" . }}-secret
  labels:
    {{- include "auth-service-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | toString | b64enc | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.env.DJANGO_DB_PASSWORD | toString | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.env.DJANGO_SUPERUSER_PASSWORD | toString | b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET_KEY: {{ .Values.env.KEYCLOAK_CLIENT_SECRET_KEY | toString | b64enc | quote }}
  KEYCLOAK_ADMIN_USERNAME: {{ .Values.env.KEYCLOAK_ADMIN_USERNAME | toString | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.env.KEYCLOAK_ADMIN_PASSWORD | toString | b64enc | quote }}
  EMAIL_HOST_USER: {{ .Values.env.EMAIL_HOST_USER | toString | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.env.EMAIL_HOST_PASSWORD | toString | b64enc | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.env.DEFAULT_FROM_EMAIL | toString | b64enc | quote }}
  EMAIL_SITE_DOMAIN: {{ .Values.env.EMAIL_SITE_DOMAIN | toString | b64enc | quote }}
  PROFILE_SERVICE_URL: {{ .Values.env.PROFILE_SERVICE_URL| toString | b64enc | quote }}
