version: '3.8'

services:
  # Сервис для парсера новостей
  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    command: go run main.go
    env_file:
      - .env
    networks:
      - app_network

  # Сервис для API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: go run main.go
    env_file:
      - .env
    networks:
      - app_network

  # Сервис для Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app_network

# Определение сетей
networks:
  app_network:
    driver: bridge

# Определение объемов
volumes:
  postgres_data:
  static_volume:
