apiVersion: v1
kind: Secret
metadata:
  name: {{ include "news-service-backend.fullname" . }}-secret
  labels:
    {{- include "news-service-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | toString | b64enc | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.env.DJANGO_DB_PASSWORD | toString | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.env.DJANGO_SUPERUSER_PASSWORD | toString | b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET_KEY: {{ .Values.env.KEYCLOAK_CLIENT_SECRET_KEY | toString | b64enc | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | toString | b64enc | quote }}
  CLIENT_ID: {{ .Values.env.CLIENT_ID | toString | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.env.CLIENT_SECRET | toString | b64enc | quote }}