# Generated by Django 5.0.8 on 2024-10-27 09:14

import profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='https://t4.ftcdn.net/jpg/08/01/47/93/360_F_801479395_lZeVjLIbUhVKS2WyYu2AqMnEBhHpv6gJ.jpg', upload_to=profile.models.user_avatar_directory_path),
        ),
    ]
