# Generated by Django 5.0.8 on 2024-10-29 15:33

import profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10, validators=[profile.validators.ProfileValidator.validate_date_format]),
        ),
    ]
