replicaCount: 1

image:
  repository: ${CI_REGISTRY_IMAGE}
  pullPolicy: IfNotPresent
  # tag: будет установлен в CI/CD пайплайне

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "service-auth-app"
  imagePullSecrets:
    - name: secret-gitlab-cicd

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: backend-auth.meerkat-code.com
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: backend-auth-meerkat-tls
     hosts:
       - backend-auth.meerkat-code.com

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - auth-service-backend
        topologyKey: "kubernetes.io/hostname"

persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 5Gi

env:
  DEBUG: "True"
  PYTHONPATH: "./"
  LANGUAGE_CODE: "ru"
  
  DJANGO_SECRET_KEY: y%4c3>dLYu3FoA?NN/yr5T/JiT_/Vy{26pufT5Mr|zk?MP(s@[2HE))W)$'
  DJANGO_SETTINGS_MODULE: "config.general_config.settings"
  DJANGO_ALLOWED_HOSTS: "*,demo.meerkat-code.com,backend-auth.meerkat-code.com,192.168.0.0/16,10.96.0.0/12,*.svc.cluster.local,localhost,127.0.0.1"
  DJANGO_DB_ENGINE: "django.db.backends.postgresql"
  DJANGO_DB_NAME: "auth_service"
  DJANGO_DB_USER: "auth"
  DJANGO_DB_PASSWORD: "PjHULxfeFhHFRhXee9c4vmP2ppXtcg"
  DJANGO_DB_HOST: "acid-postgres-cluster.postgres-cluster.svc.cluster.local"
  DJANGO_DB_PORT: "5432"
  DJANGO_SUPERUSER_PASSWORD: "gs!b@DasFh$xW2Y*gFt7!#NJFsiUas@qktsUUQxA"

  CORS_ALLOWED_ORIGINS: "https://demo.meerkat-code.com,https://meerkat-code.com,https://backend-auth.meerkat-code.com,http://localhost:5170"
  CORS_ALLOW_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  CORS_ALLOW_HEADERS: "accept, accept-encoding, authorization, content-type, dnt, origin, user-agent, x-csrftoken, x-requested-with, x-django-request-id"
  CORS_ALLOW_CREDENTIALS: "True"
  CSRF_TRUSTED_ORIGINS: "https://meerkat-code.com,https://demo.meerkat-code.com,https://backend-auth.meerkat-code.com,https://backend-profile.meerkat-code.com,http://localhost:5170"
  
  OAUTH2_ACCESS_TOKEN_EXPIRE_SECONDS: "36000"
  OAUTH2_REFRESH_TOKEN_EXPIRE_SECONDS: "1209600"
  OAUTH2_SCOPE_READ: "Read scope"
  OAUTH2_SCOPE_WRITE: "Write scope"
  OAUTH2_SCOPE_GROUPS: "Access groups"
  OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL: "oauth2_provider.AccessToken"
  OAUTH2_PROVIDER_APPLICATION_MODEL: "oauth2_provider.Application"
  OAUTH2_PROVIDER_ID_TOKEN_MODEL: "oauth2_provider.IDToken"
  OAUTH2_PROVIDER_GRANT_MODEL: "oauth2_provider.Grant"
  OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL: "oauth2_provider.RefreshToken"
  
  KEYCLOAK_SERVER_URL: "https://auth.meerkat-code.com"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_CLIENT_ID: "demo-meerkat-client"
  KEYCLOAK_CLIENT_SECRET_KEY: "FlyHQC8JNwN1Rd9RA089eYwCDbWSzj4k"
  KEYCLOAK_CACHE_TTL: "60"
  KEYCLOAK_ADMIN_USERNAME: auth-admin@meerkat-code.com
  KEYCLOAK_ADMIN_PASSWORD: akt]*P$<dN_sV/!lb/p6uX,[l.Dc0{%$76uV_4O-sA}hsCok:G0b}z
  KEYCLOAK_REDIRECT_URI: https://demo.meerkat-code.com/Auth
  LOCAL_DECODE: "False"

  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.beget.com"
  EMAIL_PORT: 2525
  EMAIL_USE_TLS: True
  EMAIL_HOST_USER: "info@meerkat-code.com"
  EMAIL_HOST_PASSWORD: "jtA4wJoP1eV&"
  DEFAULT_FROM_EMAIL: "info@meerkat-code.com"
  DEFAULT_SCHEME: "https"
  EMAIL_SITE_DOMAIN: "demo.meerkat-code.com"

  PROFILE_SERVICE_URL: "https://backend-profile.meerkat-code.com/api/profiles/"
