apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "analitik-service-backend.fullname" . }}-config
  labels:
    {{- include "analitik-service-backend.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.env.DEBUG | quote }}
  DB_ENGINE: {{ .Values.env.DB_ENGINE | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}