# Generated by Django 5.1.1 on 2024-10-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_register', '0002_customuser_confirmation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_confirmed',
        ),
    ]
