apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analitik-service-backend.fullname" . }}-secret
  labels:
    {{- include "analitik-service-backend.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | b64enc | quote }}
  DB_PASS: {{ .Values.env.DB_PASS | b64enc | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.env.DJANGO_SUPERUSER_PASSWORD | b64enc | quote }}